
tuning:
  empty:

fix:

  lr:
  blr: 5.e-4
  min_lr: 1.e-6

  weight_decay: 0.05
  weight_decay_end: 
  layer_decay: 0.65

  layer_scale_init_values: 0.1
  drop_path_rate: 0.1

  grad_clip: 1.0
  warmup_epochs: 5
  warmup_steps: -1
  epochs: 50

  if_model_ema: True
  model_ema_decay:  0.9999
  model_ema_force_cpu: False

  opt: adamw
  opt_eps: 1.e-8
  opt_betas:
  accum_iter: 1

  batch_size: 128
  early_stop_limit: 20
  smoothing: 0.1

  if_scratch: False
  if_finetune: True

  if_sandwich_norm: False
  if_causal_attention: False


  linear_prob_layer: 6

  n_class: 6
  train_ratio: 0.8
  max_scale: 1669.8225  # for BENDR
  mertric: ["accuracy", "balanced_accuracy", "cohen_kappa", "f1_weighted"]
  main_index: cohen_kappa

  num_workers: 16
  device: 'cuda'
  if_DDP: True
  seed: 0

  #data
  window_size: 1000
  stride_size: 1000
  sample_rate: 200

  config_path: ./config/TUEV_finetune.yaml
  run_escription: TUEV_finetune
  home_path: your project path
  h5_data_path: your data path
  dataset: 'TUEV'
  pretrain_config_path: ./config/pretrain_base.yaml
  vvqgan_model_path: './checkpoints/base_class_quantization.pth'

#ch_list
  RUIJIN: ['FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2', 'F7', 'F8', 'T7', 'T8', 'P7', 'P8', 'FZ', 'CZ', 'PZ'] #t3->t7 t4->t8 t5->p7 t6->p8
  TUAB: ['FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2', 'F7', 'F8', 'T7', 'T8', 'P7', 'P8', 'FZ', 'CZ', 'PZ']  #t3->t7 t4->t8 t5->p7 t6->p8
  TUSZ: ['FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2', 'F7', 'F8','T7', 'T8', 'P7', 'P8', 'CZ']  #t3->t7 t4->t8 t5->p7 t6->p8
  TUEV: ['FP1', 'FP2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4', 'O1', 'O2', 'F7', 'F8', 'T7', 'T8', 'P7', 'P8', 'FZ', 'CZ', 'PZ'] 
  all_ch_list: [
    'FP1', 'FPZ', 'FP2', 
    'AF9', 'AF7', 'AF5', 'AF3', 'AF1', 'AFZ', 'AF2', 'AF4', 'AF6', 'AF8', 'AF10', 
    'F9', 'F7', 'F5', 'F3', 'F1', 'FZ', 'F2', 'F4', 'F6', 'F8', 'F10', 
    'FT9', 'FT7', 'FC5', 'FC3', 'FC1', 'FCZ', 'FC2', 'FC4', 'FC6', 'FT8', 'FT10', 
    'T9', 'T7', 'C5', 'C3', 'C1', 'CZ', 'C2', 'C4', 'C6', 'T8', 'T10', 
    'TP9', 'TP7', 'CP5', 'CP3', 'CP1', 'CPZ', 'CP2', 'CP4', 'CP6', 'TP8', 'TP10', 
    'P9', 'P7', 'P5', 'P3', 'P1', 'PZ', 'P2', 'P4', 'P6', 'P8', 'P10', 
    'PO9', 'PO7', 'PO5', 'PO3', 'PO1', 'POZ', 'PO2', 'PO4', 'PO6', 'PO8', 'PO10', 
    'O1', 'OZ', 'O2', 'O9', 'CB1', 'CB2', 
    'IZ', 'O10', 'T3', 'T5', 'T4', 'T6', 'M1', 'M2', 'A1', 'A2', 
    'CFC1', 'CFC2', 'CFC3', 'CFC4', 'CFC5', 'CFC6', 'CFC7', 'CFC8', 
    'CCP1', 'CCP2', 'CCP3', 'CCP4', 'CCP5', 'CCP6', 'CCP7', 'CCP8', 
    'T1', 'T2', 
    "FP1-F7", "F7-T7", "T7-P7", "P7-O1", "FP2-F8", "F8-T8", "T8-P8", "P8-O2", "FP1-F3", "F3-C3", "C3-P3", "P3-O1", "FP2-F4", "F4-C4", "C4-P4", "P4-O2"
]